# Generated by Django 4.0.4 on 2022-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel_output', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='first_exel_file',
            field=models.FileField(unique=True, upload_to='exel/first'),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='second_exel_file',
            field=models.FileField(unique=True, upload_to='exel/second'),
        ),
    ]
