# Generated by Django 4.0.4 on 2022-05-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel_output', '0002_alter_uploader_first_exel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='first_exel_file',
            field=models.FileField(upload_to='exel/first'),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='second_exel_file',
            field=models.FileField(upload_to='exel/second'),
        ),
    ]
