# Generated by Django 4.0.4 on 2022-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel_output', '0003_alter_uploader_first_exel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploader',
            name='out_file',
            field=models.FileField(null=True, upload_to='out/'),
        ),
    ]
