# Generated by Django 4.0.4 on 2022-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel_output', '0004_uploader_out_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='uploader',
            name='first_exel_file',
            field=models.FileField(upload_to='exel/'),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='second_exel_file',
            field=models.FileField(upload_to='exel/'),
        ),
    ]
